ignore: null

exclude:
  - /^contao\/languages/

mapping:
  'Andreas Isaak <info@andreas-isaak.de>':
    - 'Andreas Isaak <andy.jared@googlemail.com>'
  'Stefan Heimes <stefan_heimes@hotmail.com>':
    - 'Stefan heimes <stefan_heimes@hotmail.com>'
    - 'chibineko <stefan_heimes@hotmail.com>'
    - 'stefanheimes <stefan_heimes@hotmail.com>'
    - 'Stefan Heimes <cms@men-at-work.de>'
  'David Maack <david.maack@arcor.de>':
    - 'David Maack <maack@men-at-work.de>'
  'Christopher Boelter <christopher@boelter.eu>':
    - 'cboelter <christopher@boelter.eu>'
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'xantippe <info@e-spin.de>'
    - 'zonky2 <info@e-spin.de>'
