ignore:
#  Mini Model <minimodel@metamodel.me>

exclude:
  languages

mapping:
  Andreas Isaak <info@andreas-isaak.de>: Andreas Isaak <andy.jared@googlemail.com>
  Christopher Boelter <christopher@boelter.eu>: cboelter <christopher@boelter.eu>
